info:
  name: Create Job Application
  type: http
  seq: 1

http:
  method: POST
  url: http://localhost:8000/api/job-applications
  headers:
    - name: Authorization
      value: Bearer 3|fEB4wV5IvmrG7somSn92qOiaYXD6ltlRZ9nXcXvvdfb3ca53
  body:
    type: json
    data: |-
      {
        "email": "admin@ozsut.com",
        "password": "12345678"
      }
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
