info:
  name: Create Job Application
  type: http
  seq: 1

http:
  method: GET
  url: http://127.0.0.1:8000/api/job-applications/archive
  headers:
    - name: Accept
      value: application/json
  body:
    type: json
    data: |-
      {
        "email": "admin@ozsut.com",
        "password": "12345678"
      }
  auth:
    type: bearer
    token: 50|48Ovd9AUTLsuBUrUS1sWh02JPzWJb6cFUMggOmve15647ced

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
